FROM dockcross/android-arm64

ENV ARCH aarch64

RUN git clone https://github.com/Maratyszcza/NNPACK.git
WORKDIR /work/NNPACK

RUN mkdir build
WORKDIR /work/NNPACK/build/

RUN cmake -DBUILD_GMOCK=0 \
          -DCMAKE_INSTALL_PREFIX=/work/lib_nnpack/ \
          -DNNPACK_BUILD_TESTS=0 \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_TOOLCHAIN=clang \
          -DNNPACK_INFERENCE_ONLY=1 .. && \
    make -j$(nproc) && make install

